server:
  port: 8081
spring:
  application:
    name: user-service
  data:
    mongodb:
      auto-index-creation: true
auth:
  jwt:
    enabled: true
    # can be a comma-separated list of keys in the format <keyId>:<alg>:<key>
    # this is useful for rotating keys
    keys: ${JWT_KNOWN_KEYS:'7af3950b:HS256:bG9jYWwtbm90LXNlY3VyZS1qd3Qtc2VjcmV0LWtleQ'}
    generator:
      enabled: true
      issuer: ${JWT_ISSUER:user.local.jwt.example.dburyak.com}
      key: ${JWT_SIGN_KEY:'7af3950b:HS256:bG9jYWwtbm90LXNlY3VyZS1qd3Qtc2VjcmV0LWtleQ'}
      ttl: ${JWT_TTL:1h}
    service-token:
      enabled: true
      issuer: ${JWT_ISSUER:user.local.jwt.example.dburyak.com}
service-client:
  auth:
    enabled: true
    url: ${AUTH_SERVICE_URL:http://localhost:8080}
