server:
  port: 8083
spring:
  application:
    name: email-service
  data:
    mongodb:
      database: ${MONGO_DATABASE:local-jwt-email}
mongock:
  migration-scan-package: com.dburyak.example.jwt.email.repository.migration
auth:
  jwt:
    keys: ${JWT_KNOWN_KEYS:'7af3950b:HS256:bG9jYWwtbm90LXNlY3VyZS1qd3Qtc2VjcmV0LWtleQ'}
    trusted-issuers:
      - local.jwt.example.dburyak.com
      - user.local.jwt.example.dburyak.com
