server:
  port: 8084
spring:
  application:
    name: otp-service
  data:
    mongodb:
      database: ${MONGO_DATABASE:local-jwt-otp}
mongock:
  migration-scan-package: com.dburyak.example.jwt.otp.repository.migration
auth:
  jwt:
    keys: ${JWT_KNOWN_KEYS:'7af3950b:HS256:bG9jYWwtbm90LXNlY3VyZS1qd3Qtc2VjcmV0LWtleQ'}
